apiVersion: v1
kind: Namespace
metadata:
  name: chartmuseum
  labels:
    name: chartmuseum

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv
  labels:
    app: chartmuseum
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/chartmuseum-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role
          operator: In
          values:
          - worker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-pvc
  namespace: chartmuseum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  namespace: chartmuseum
  labels:
    app: chartmuseum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      labels:
        app: chartmuseum
    spec:
      nodeSelector:
        node-role: worker
      containers:
      - name: chartmuseum
        image: chartmuseum/chartmuseum:v0.15.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DISABLE_API
          value: "false"
        - name: ALLOW_OVERWRITE
          value: "true"
        - name: STORAGE
          value: local
        - name: STORAGE_LOCAL_ROOTDIR
          value: /charts
        - name: CHART_POST_FORM_FIELD_NAME
          value: chart
        - name: PROV_POST_FORM_FIELD_NAME
          value: prov
        volumeMounts:
        - name: chartmuseum-storage
          mountPath: /charts
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: chartmuseum-storage
        persistentVolumeClaim:
          claimName: chartmuseum-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  namespace: chartmuseum
  labels:
    app: chartmuseum
spec:
  selector:
    app: chartmuseum
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum-external
  namespace: chartmuseum
  labels:
    app: chartmuseum
spec:
  selector:
    app: chartmuseum
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
  type: NodePort 