apiVersion: v1
kind: Namespace
metadata:
  name: helm-repository
  labels:
    name: helm-repository

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  namespace: helm-repository
  labels:
    app: chartmuseum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      labels:
        app: chartmuseum
    spec:
      nodeSelector:
        node-role: worker
      containers:
      - name: chartmuseum
        image: ghcr.io/helm/chartmuseum:v0.15.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DISABLE_API
          value: "false"
        - name: ALLOW_OVERWRITE
          value: "true"
        - name: STORAGE
          value: "memory"
        - name: DEBUG
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  namespace: helm-repository
  labels:
    app: chartmuseum
spec:
  selector:
    app: chartmuseum
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum-external
  namespace: helm-repository
  labels:
    app: chartmuseum
spec:
  selector:
    app: chartmuseum
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
  type: NodePort 