# PostgreSQL Helm Chart Values
# Replaces 185 lines of custom YAML with this configuration

# Authentication
auth:
  enablePostgresUser: true
  # postgresPassword: Set via --set flag during deployment for security
  username: "postgres"
  database: "shared_db"

# Persistence - using local storage like current setup
primary:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "local-storage"
    
  # Distribute across worker nodes (avoid master for data workloads)
  nodeSelector:
    node-role: worker
    
  # Resource limits optimized for worker nodes
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  ports:
    postgresql: 5432

# External access via NodePort (distributed across cluster)
# We'll create a separate NodePort service for external access
metrics:
  enabled: true
  serviceMonitor:
    enabled: true 