apiVersion: v1
kind: Service
metadata:
  name: tweetstream-backend-nodeport
  namespace: default
  labels:
    app: tweetstream-backend
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: tweetstream-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30950
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: tweetstream-frontend-nodeport
  namespace: default
  labels:
    app: tweetstream-frontend
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: tweetstream-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30951
    protocol: TCP
    name: http 