apiVersion: v1
kind: Namespace
metadata:
  name: kuberay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: kuberay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberay-operator
  template:
    metadata:
      labels:
        app: kuberay-operator
    spec:
      serviceAccountName: kuberay-operator
      containers:
      - name: kuberay-operator
        image: kuberay/operator:nightly
        imagePullPolicy: Always
        env:
        - name: RAY_CLUSTER_CRD_NAMESPACED
          value: "true"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberay-operator
  namespace: kuberay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberay-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["ray.io"]
  resources: ["rayclusters", "rayservices", "rayjobs"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberay-operator
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: kuberay
roleRef:
  kind: ClusterRole
  name: kuberay-operator
  apiGroup: rbac.authorization.k8s.io 