apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: platform-services
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30432
  type: NodePort 