apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: platform-services
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379
  type: NodePort 